runtime: nodejs20
entrypoint: node server/app.js
handlers:
  - url: /api/.*
    script: auto
    secure: always

  - url: /auth/.*
    script: auto
    secure: always

  - url: /(.*\.(js|css|wasm|png|jpg|jpeg|gif|svg))
    static_files: client/dist/\1
    upload: client/dist/.*\.(js|css|wasm|png|jpg|jpeg|gif|svg)
    secure: always

  # SPA fallback
  - url: /.*
    static_files: client/dist/index.html
    upload: client/dist/index.html
    secure: always