options:
  defaultLogsBucketBehavior: "REGIONAL_USER_OWNED_BUCKET"

steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install'] # npm install

  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'bash'
    env:
      - 'HOME=/root'
    args:
      - '-c'
      - |
        curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path
        source $HOME/.cargo/env
        cargo install wasm-pack

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build'] # npm run build

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet'] # gcloud app deploy

timeout: '900s'