options:
  defaultLogsBucketBehavior: "REGIONAL_USER_OWNED_BUCKET"

steps:
  - name: 'rustwasm/wasm-pack:latest'
    id: build-wasm
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd client/rust
        wasm-pack build --release --target web --out-dir ../../pkg

  - name: 'gcr.io/cloud-builders/npm'
    args: ['install'] # npm install

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build'] # npm run build

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet'] # gcloud app deploy

timeout: '900s'