options:
  defaultLogsBucketBehavior: "REGIONAL_USER_OWNED_BUCKET"

steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install'] # npm install

  - name: 'docker.io/library/rust:1.83-slim'     # official Docker Hub image
    id: build-wasm
    entrypoint: bash
    args:
      - -c
      - |
        cargo install wasm-pack --version 0.13.1
        wasm-pack build client/rust --release --target web --out-dir /workspace/client/pkg

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build'] # npm run build

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet'] # gcloud app deploy

timeout: '900s'